# Generated by Django 3.2 on 2021-05-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20210513_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='File',
            field=models.FileField(upload_to='Avatar'),
        ),
    ]
