# Generated by Django 3.2 on 2021-05-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='File',
            field=models.FileField(upload_to='Document'),
        ),
    ]
